name: End to End API Automation for Usermanagement APIs
on:
  workflow_dispatch:
    inputs:
      profile:
        description: Env to run test on
        required: true
        default: 'sit'
        type: choice
        options:
          -  dev
          -  sit
          -  uat
      suite:
        description: Test Suite to run
        required: true
        default: 'smoke'
        type: choice
        options:
          -  Regression
          -  Smoke
          -  Sanity
        

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: Execute End to End API Script
        run: |
          java --version
          mvn clean test -Pdev -Dsuite=Regression
      -  name: Upload artifact
         if: always()
         uses: actions/upload-artifact@v4
         with:
          name: test-log
          path: log
      
