name: End to End API Automation for Usermanagement APIs
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: Execute End to End API Script
        run: mvn clean test -Pdev -Dsuite=Regression
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: log
